(function(a){a.fn.fitVids=function(c){var b={customSelector:null,ignore:null};if(!document.getElementById("fit-vids-style")){var d=document.head||document.getElementsByTagName("head")[0],f=document.createElement("div");f.innerHTML='<p>x</p><style id="fit-vids-style">.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}</style>';
d.appendChild(f.childNodes[1])}c&&a.extend(b,c);return this.each(function(){var e="iframe[src*='player.vimeo.com'] iframe[src*='youtube.com'] iframe[src*='youtube-nocookie.com'] iframe[src*='kickstarter.com'][src*='video.html'] object embed".split(" ");b.customSelector&&e.push(b.customSelector);var c=".fitvidsignore";b.ignore&&(c=c+", "+b.ignore);e=a(this).find(e.join(","));e=e.not("object object");e=e.not(c);e.each(function(){var e=a(this);if(!(0<e.parents(c).length)&&!("embed"===this.tagName.toLowerCase()&&
e.parent("object").length||e.parent(".fluid-width-video-wrapper").length)){if(!e.css("height")&&!e.css("width")&&(isNaN(e.attr("height"))||isNaN(e.attr("width"))))e.attr("height",9),e.attr("width",16);var b="object"===this.tagName.toLowerCase()||e.attr("height")&&!isNaN(parseInt(e.attr("height"),10))?parseInt(e.attr("height"),10):e.height(),d=!isNaN(parseInt(e.attr("width"),10))?parseInt(e.attr("width"),10):e.width(),b=b/d;e.attr("id")||(d="fitvid"+Math.floor(999999*Math.random()),e.attr("id",d));
e.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",100*b+"%");e.removeAttr("height").removeAttr("width")}})})}})(window.jQuery||window.Zepto);(function(){angular.module("common","vcRecaptcha common.account common.camps common.community common.courseCatalog common.hackathons common.hourOfCode common.marketing common.school common.minecraft common.projects common.rating common.sharing common.weeklyProjects".split(" "))})();
(function(){angular.module("common.account",["common"])})();
(function(){angular.module("common.account").controller("AccountCtrl",["$scope","$http","$state","api","externalAuth",function(a,c,b,d,f){a.state=b;a.error=null;a.busy=!1;a.signupUser=function(e){a.busy=!0;return d.addUser(e).then(function(){a.busy=!1;a.onLoginSuccess()},function(e){a.busy=!1;a.error=e})};a.validateUsername=function(a,b){a?6>a.length?b("Screen name must have at least 6 characters"):c({method:"GET",url:"/api/validateusername",params:{u:a}}).success(function(a){"true"==a?b("Looking good!"):
b("Sorry, that screen name is already taken.")}):b("You must provide a screen name")};a.validatePassword=function(a,b){a?6>a.length?b("Password must have at least 6 characters"):b("Ok!"):b("You must provide a password.")};a.validateEmail=function(a,b){a?-1==a.indexOf("@")?b("Doesn't look like a valid email"):c({method:"GET",url:"/api/validateemail?email="+a}).success(function(a){a.is_valid?b("Ok"):b("Doesn't look like a valid email")}):b("You must provide a valid email address")};a.googleLogin=function(){f.googleLogin().then(function(){a.onLoginSuccess()},
function(e){a.error=e})};a.azureLogin=function(){f.azureLogin().then(function(){a.onLoginSuccess()},function(e){a.error=e})};a.onLoginSuccess=function(){$(document).trigger("common.account.loggedIn")};a.$on("$viewContentLoaded",function(){setTimeout(function(){$("#signup-view > .modal").modal()},0)})}])})();
(function(){angular.module("common.account").controller("AskParentCtrl",["$scope","$stateParams","api",function(a,c,b){a.activitySlug=c.activitySlug?c.activitySlug:null;a.error=null;a.parentEmail=null;a.sent=!1;a.askParent=function(c,f){a.error=null;a.isLoading=!0;b.sendParentPermissionRequest(c,f).then(function(){a.isLoading=!1;a.sent=!0;angular.element.cookie("submitted_ask_parent",!0,{expires:3650,path:"/"})},function(e){a.isLoading=!1;a.error=e})}}]).controller("JoinNewsletterCtrl",["$scope",
"$stateParams","api",function(a,c,b){a.email=null;a.error=null;a.role=c.role?c.role:"parent";a.sent=!1;a.steps=["join","profile","thanks"];a.step="join";a.fname=null;a.lname=null;a.joined=!1;a.joining=!1;a.init=function(b){a.email=b};a.join=function(c){b.addSubscription({email:c.email,role:c.role,strict:!1,type:"email-collector-modal"}).then(function(b){a.subscriptionId=b;a.step="profile";a.error=null;ga("send","event","Join Newsletter Modal","Submit");angular.element.cookie("submitted_join_newsletter",
!0,{expires:3650})},function(b){a.error=b})};a.updateProfile=function(c){b.updateSubscription(a.subscriptionId,{fname:c.fname,lname:c.lname,email:c.email,role:c.role,strict:!1,type:"email-collector-modal"}).then(function(){a.error=null;a.step="thanks";ga("send","event","Join Newsletter Modal","Complete")})};a.joinFull=function(){a.joining=!0;b.addSubscription({email:a.email,role:a.role,strict:!1,type:"email-collector-modal"}).then(function(){console.info("worked");a.error=null;a.joining=!1;a.joined=
!0;ga("send","event","Hour of Code Congrats Page","Join Newsletter")},function(b){console.info(b);a.error=b;a.joining=!1})}}])})();
(function(){function a(){return{bindToController:{onClickAzureLoginRole:"=?",onClickAzureLoginNext:"=?"},controller:c,controllerAs:"vm",restrict:"A",link:function(a,c,f,e){c.click(function(){e.azureLogin({role:f.onClickAzureLoginRole,next:f.onClickAzureLoginNext})})}}}function c(a,c){var f=this;f.azureLogin=function(e){e=void 0!==e?e:{};e.next||(e.next=a.absUrl());c.azureLogin(e).then(function(){f.onLoginSuccess(e.next)},function(a){f.error=a})}}angular.module("common.account").directive("onClickAzureLogin",
a);a.$inject=[];c.$inject=["$location","externalAuth"]})();
(function(){function a(a,b,d,f){var e=this;e.facebookLogin=function(){f.facebookLogin({childConfCode:e.user.childConfCode,role:"parent",source:"verify-parent"}).then(function(){e.onLoginSuccess()},function(a){e.error=a})};e.googleLogin=function(){f.googleLogin({childConfCode:e.user.childConfCode,role:"parent",source:"verify-parent"}).then(function(){e.onLoginSuccess()},function(a){e.error=a})};e.azureLogin=function(){f.azureLogin({childConfCode:e.user.childConfCode,role:"parent",source:"verify-parent"}).then(function(){e.onLoginSuccess()},
function(a){e.error=a})};e.hasNext=function(){return e.steps.indexOf(e.step)+1<e.steps.length};e.hasPrevious=function(){return 0<e.steps.indexOf(e.step)};e.init=function(b,f){d.ga("send","event","Sign-up Modal","Parent Verified Student");e.step="welcome";e.user.username=b;e.user.childConfCode=f;a.$watch("step",function(){angular.element("body").animate({scrollTop:0},"slow")})};e.next=function(){var a=e.steps.indexOf(e.step);a==e.steps.length-1?e.signupUser(e.user):e.step=e.steps[a+1]};e.previous=
function(){var a=e.steps.indexOf(e.step);0==a?b.go("join"):e.step=e.steps[a-1]};e.setShowTynkerSignup=function(a){e.showTynkerSignup=a};e.showTynkerSignup=!1;e.steps=["welcome","account","details"];e.step=null;e.user={role:"parent",log_in:!0,convert:!0,confirmed:!0,source:"verify-parent"}}angular.module("common.account").controller("ParentVerifyController",a);a.$inject=["$scope","$state","$window","externalAuth"]})();
(function(){function a(a,b,d){var f=this;f.activitySlug=b.activitySlug?b.activitySlug:null;f.activity=null;f.init=function(){a.$watch("activitySlug",function(){f.activitySlug?d.getActivity(f.activitySlug).then(function(a){f.activity=a}):f.activity=null})};f.init()}angular.module("common.account").controller("UnlockController",a);a.$inject=["$scope","$stateParams","api"]})();
(function(){angular.module("common.account").controller("VerifyEmailCtrl",["$scope","api",function(a,c){a.email=null;a.error=null;a.userId=null;a.busy=!1;a.isEditing=!1;a.firstEdit=!0;a.init=function(b){a.userId=b;c.getMyEmail().then(function(b){a.email=b;a.error=null},function(b){a.email="Could not retrieve email";a.error="Problem retrieving email: "+b;a.busy=!0})};a.resend=function(){a.busy=!0;c.resendVerificationEmail(a.userId,a.email,a.captcha).then(function(){a.busy=!1;a.error=null;a.notice=
"Sent!";a.isEditing=!1},function(b){a.busy=!1;a.error=b})};a.edit=function(){a.isEditing=!0;a.firstEdit=!1;a.error=!1;a.notice=!1}}])})();(function(){angular.module("common.camps",[])})();(function(){angular.module("common.sharing",[])})();
(function(){angular.module("common.sharing").controller("PuzzleSharingCtrl",["$scope","$http","$location",function(a,c,b){a.shareUrl=null;a.screenShot=null;a.facebookAppId=null;a.imageKey=null;a.init=function(b){a.facebookAppId=b};a.show=function(b,c,e){a.puzzleTitle=b;a.shareUrl=c;a.screenShot=e;$("#sharing").modal()};a.hide=function(){$.modal.close()};a.reset=function(){a.error=null;a.success=null};a.facebookShare=function(){shareFacebook(a.shareUrl,{appId:a.facebookAppId,serverName:b.host()})};
a.twitterShare=function(){shareTwitter(a.shareUrl,"I enjoyed solving "+a.puzzleTitle+", a coding puzzle. Try it here",{serverName:b.host(),hashTags:"hourofcode,tynker"})};a.googlePlusShare=function(){shareGooglePlus(a.shareUrl,{serverName:b.host()})}}])})();
(function(){angular.module("common.sharing").directive("shareNotebook",function(){return{controller:["modalShareNotebook",function(a){this.share=function(c,b){a.open({id:c,name:b})}}],restrict:"A",link:function(a,c,b,d){c.click(function(){d.share(b.shareNotebook,b.notebookName)})}}})})();
(function(){angular.module("common.sharing").directive("shareProject",[function(){return{controller:["modalShareProject",function(a){this.share=function(c,b){a.open({projectId:c,projectName:b})}}],restrict:"A",link:function(a,c,b,d){c.click(function(){d.share(b.shareProject,b.projectName)})}}}])})();
(function(){angular.module("common.sharing").controller("ShareAssetPopupCtrl",["$scope","$http","$location","$window","api",function(a,c,b,d,f){function e(a){a=a.trim().toLowerCase();a=a.replace(/[^a-zA-Z0-9]/g,"-");(a=a.replace(/--+/g,"-"))||(a="default");return a}function g(a,b,c,d){switch(a){case "skin":return"/minecraft/skins/view/"+e(c)+"/"+b;case "item":return"/minecraft/items/view/"+d+"/"+e(c)+"/"+b;case "block":return"/minecraft/blocks/view/"+d+"/"+e(c)+"/"+b;case "entity":return"/minecraft/mobs/view/"+
d+"/"+e(c)+"/"+b}}function h(a,b){switch(a){case "skin":return"/minecraft/api/skin?id="+b+"&w=40&h=35";case "block":return"/minecraft/api/block?id="+b+"&w=40&h=35";case "item":return"/minecraft/api/item?id="+b+"&w=40&h=35";case "entity":if(d.g_entityCapture)return d.g_entityCapture();default:return null}}a.assetId=null;a.assetName=null;a.assetTitle=null;a.assetType=null;a.assetImage=null;a.shared=!1;a.captchaCode=null;a.captchaRandom=null;a.currentTab=null;a.tabs={};a.serverName=null;a.busy=!1;a.generateCaptcha=
function(){a.captchaRandom="/api/captcha?r="+Math.random();a.captchaCode=null};a.init=function(e,c,d,f,g){a.facebookAppId=e;a.serverName=b.host();if("student"==c&&!d){if(a.tabs={community:"Community"},a.currentTab="community",f||g)a.tabs.connections="Connected to Me"}else a.tabs={social:"Social"},a.currentTab="social"};a.show=function(b,e,c,l,m){d.ga("send","event","Minecraft Share Modal","Open","entity"==b?"mob":b);a.error="";a.success="";a.assetId=e;a.assetName=m;a.assetTitle=c;a.assetType=b;a.assetImage=
l?l:h(b,e);a.assetShareUrl="https://"+a.serverName+g(b,e,c,m);a.generateCaptcha();"entity"==b?f.saveImage(e,a.assetImage).then(function(){$("#share-asset-popup").modal()},function(){$("#share-asset-popup").modal()}):$("#share-asset-popup").modal()};a.hide=function(){$.modal.close()};a.reset=function(){a.error=null;a.success=null};a.setCurrentTab=function(b){a.currentTab=b};a.communityShare=function(){d.ga("send","event","Minecraft Share Modal","Share","Community");a.busy=!0;f.shareAssetToCommunity(a.assetType,
a.assetId).then(function(){a.busy=!1;a.error="";a.success="Successfully published!";a.shared=!0},function(b){a.busy=!1;a.success="";a.error=b})};a.communityUnshare=function(){d.ga("send","event","Minecraft Share Modal","Unshare","Community");a.busy=!0;f.unshareAssetFromCommunity(a.assetType,a.assetId).then(function(){a.busy=!1;a.error="";a.success="Successfully unpublished!";a.shared=!1},function(b){a.busy=!1;a.success="";a.error=b})};a.emailParent=function(){d.ga("send","event","Minecraft Share Modal",
"Share","Email Parent");a.busy=!0;f.sendMinecraftAssetEmail(a.assetId).then(function(){a.busy=!1;a.error="";a.success="Shared successfully!"},function(b){a.busy=!1;a.success="";a.error=b})};a.emailShare=function(){d.ga("send","event","Minecraft Share Modal","Share","Email");a.busy=!0;f.sendMinecraftAssetEmail(a.assetId,a.displayName,a.email,a.captchaCode,a.assetShareUrl,a.assetImage).then(function(){a.busy=!1;a.success="Shared successfully!"},function(b){a.busy=!1;a.error=b;a.generateCaptcha()})};
a.facebookShare=function(){d.ga("send","event","Minecraft Share Modal","Share","Facebook");shareFacebook(a.assetShareUrl,{appId:a.facebookAppId,serverName:b.host()})};a.twitterShare=function(){d.ga("send","event","Minecraft Share Modal","Share","Twitter");shareTwitter(a.assetShareUrl,a.assetTitle,{serverName:b.host(),hashTags:"tynker,minecraft,"+("entity"==a.assetType?"mob":a.assetType)})};a.googlePlusShare=function(){d.ga("send","event","Minecraft Share Modal","Share","Google+");shareGooglePlus(a.assetShareUrl)}}])})();
(function(){angular.module("common.sharing").directive("shareBar",[function(){return{controller:["$scope",function(a){a.shareEmail=function(){shareEmail(a.text,a.url)};a.shareFacebook=function(){shareFacebook(a.url,{appId:a.facebookAppId})};a.shareGooglePlus=function(){shareGooglePlus(a.url)};a.shareTwitter=function(){shareTwitter(a.url,a.text,{serverName:a.serverName})}}],restrict:"E",scope:{facebookAppId:"@",serverName:"@",text:"=",url:"="},templateUrl:"/js/ng-app/common/sharing/shareBar.directive.html"}}])})();
(function(){angular.module("common.sharing").directive("sharePageEmail",[function(){return{controller:["$location","social",function(a,c){this.share=function(b,d,f){b=b?b:a.absUrl();c.shareEmail(d,f+("\n"+b))}}],restrict:"A",link:function(a,c,b,d){c.click(function(){d.share(b.url,b.subject,b.body)})}}}])})();
(function(){angular.module("common.sharing").directive("sharePageFacebook",[function(){return{controller:["$location","social",function(a,c){this.share=function(b){b=b?b:a.absUrl();c.shareFacebook(b)}}],restrict:"A",link:function(a,c,b,d){c.click(function(){d.share(b.url)})}}}])})();
(function(){angular.module("common.sharing").directive("sharePageGooglePlus",[function(){return{controller:["$location","social",function(a,c){this.share=function(b){b=b?b:a.absUrl();c.shareGooglePlus(b)}}],restrict:"A",link:function(a,c,b,d){c.click(function(){d.share(b.url)})}}}])})();
(function(){angular.module("common.sharing").directive("sharePageTwitter",[function(){return{controller:["$location","social",function(a,c){this.share=function(b,d,f){var b=b?b:a.absUrl(),e={};f&&(e.hashTags=f);c.shareTwitter(b,d,e)}}],restrict:"A",link:function(a,c,b,d){c.click(function(){d.share(b.url,b.text,b.hashTags)})}}}])})();
(function(){angular.module("common.sharing").controller("SharePopupCtrl",["$scope","$http","$location","$window","api",function(a,c,b,d,f){a.projectId=null;a.projectName=null;a.projectScreenShot=null;a.currentTab=null;a.tabs={};a.captchaCode=null;a.captchaRandom=null;a.displayName=null;a.email=null;a.serverName=null;a.facebookAppId=null;a.stageWidth=660;a.stageHeight=408;a.shared=!1;a.busy=!1;a.init=function(e,c,d,f,j){a.facebookAppId=e;a.serverName=b.host();if("student"==c){a.tabs={embed:"Embed"};
a.currentTab="email";if(f||j)a.tabs.connections="Connected to Me",a.currentTab="connections";a.tabs.community="Community";a.currentTab="community";d&&(a.tabs.email="Email")}else a.tabs={community:"Community",email:"Email",embed:"Embed",social:"Social"},a.currentTab="social"};a.show=function(b,c,f){requests.get("/api/genshareurl",{id:b}).then(function(i){f=f?f:"https://"+a.serverName+"/play/"+b+"-"+i.data.hash;d.ga("send","event","Project Share Modal","Open",c);a.error="";a.success="";a.projectId=
b;a.projectName=c;a.projectShareUrl=f;a.projectScreenShot="/assets/pscreenshot/"+b+".png?f=true";a.generateCaptcha();$("#share-popup").modal()})};a.hide=function(){$.modal.close()};a.reset=function(){a.error=null;a.success=null;a.email=null;a.generateCaptcha()};a.setCurrentTab=function(b){a.currentTab=b};a.emailParent=function(){d.ga("send","event","Project Share Modal","Share","Email Parent");a.busy=!0;f.sendProjectEmail(a.projectId).then(function(){a.busy=!1;a.error="";a.success="Shared successfully!"},
function(b){a.busy=!1;a.success="";a.error=b})};a.communityShare=function(){d.ga("send","event","Project Share Modal","Share","Community");a.busy=!0;f.shareToCommunity(a.projectId).then(function(){a.busy=!1;a.error="";a.success="Successfully published!";a.shared=!0},function(b){a.busy=!1;a.success="";a.error=b})};a.communityUnshare=function(){d.ga("send","event","Project Share Modal","Unshare","Community");a.busy=!0;f.unshareFromCommunity(a.projectId).then(function(){a.busy=!1;a.error="";a.success=
"Successfully unpublished!";a.shared=!1},function(b){a.busy=!1;a.success="";a.error=b})};a.parentShare=function(){d.ga("send","event","Project Share Modal","Share","Parent");a.busy=!0;f.addToGallery(a.projectId,"home").then(function(){a.busy=!1;a.error="";a.success="Shared successfully!"},function(b){a.busy=!1;a.success="";a.error=b})};a.classShare=function(){d.ga("send","event","Project Share Modal","Share","Class");a.busy=!0;f.addToGallery(a.projectId,"class").then(function(){a.busy=!1;a.error=
"";a.success="Shared successfully!"},function(b){a.busy=!1;a.success="";a.error=b})};a.emailShare=function(){d.ga("send","event","Project Share Modal","Share","Email");a.busy=!0;f.sendProjectEmail(a.projectId,a.displayName,a.email,a.captchaCode,a.projectShareUrl).then(function(){a.busy=!1;a.success="Shared successfully!"},function(b){a.busy=!1;a.error=b;a.generateCaptcha()})};a.facebookShare=function(){d.ga("send","event","Project Share Modal","Share","Facebook");shareProjectFacebook(a.projectId,
{appId:a.facebookAppId,serverName:b.host(),shareUrl:a.projectShareUrl})};a.twitterShare=function(){d.ga("send","event","Project Share Modal","Share","Twitter");shareProjectTwitter(a.projectId,a.projectName,a.projectDescription,{serverName:b.host(),shareUrl:a.projectShareUrl})};a.googlePlusShare=function(){d.ga("send","event","Project Share Modal","Share","Google+");shareProjectGooglePlus(a.projectId,{serverName:b.host(),shareUrl:a.projectShareUrl})};a.generateCaptcha=function(){a.captchaRandom="/api/captcha?r="+
Math.random();a.captchaCode=null}}])})();
(function(){angular.module("common.sharing").controller("SharingCtrl",["$scope","$http","$location","api",function(a,c,b,d){a.projectId=null;a.projectName=null;a.projectScreenShot=null;a.currentTab=null;a.tabs={};a.captchaCode=null;a.captchaRandom=null;a.displayName=null;a.email=null;a.facebookAppId=null;a.stageWidth=null;a.stageHeight=null;a.busy=!1;a.init=function(b,c){a.facebookAppId=b;if("student"==c){a.tabs={community:"Community",embed:"Embed"};a.currentTab="email";prefs.defaultGalleryId&&(a.tabs.gallery=
"Showcase",a.currentTab="gallery");if(prefs.hasClass||prefs.hasParent)a.tabs.connections="Connected to Me",a.currentTab="connections";prefs.isAnon&&(a.tabs.email="Email")}else a.tabs={community:"Community",email:"Email",embed:"Embed",social:"Social"},a.currentTab="social",prefs.defaultGalleryId&&(a.tabs.gallery="Showcase",a.currentTab="gallery");a.currentTab="community"};a.show=function(){if(!IDE.currentProjectId||!IDE.currentProjectName){var c=$("#sharing-set-title").scope();c&&c.show()}else IDE.isDirty?
(Runtime.stage.selectActor(null),c=Runtime.stage.captureScreenshot(),IDE._doProjectSave(null,null,c,!0,!0,function(c){c&&b.search({p:IDE.currentProjectId});a._show()})):a._show()};a._show=function(){Runtime.stage.selectActor(null);var b=Runtime.stage.captureScreenshot();a.generateCaptcha();a.stageWidth=Runtime.stage.getWidth();a.stageHeight=Runtime.stage.getHeight();a.projectId=IDE.currentProjectId;a.projectName=IDE.currentProjectName;a.projectDescription=IDE.currentProjectDescription;a.projectScreenShot=
b;$("#sharing").modal()};a.hide=function(){$.modal.close()};a.reset=function(){a.error=null;a.success=null;a.email=null;a.generateCaptcha()};a.setCurrentTab=function(b){a.currentTab=b};a.communityShare=function(b){a.busy=!0;d.shareToCommunity(a.projectId,b).then(function(){a.busy=!1;a.error="";a.success2="Successfully published!";a.published=!0},function(b){a.busy=!1;a.success2="";a.error=b})};a.ideCommunityShare=function(){IDE.cmdProjectSubmitEntry("system-summer-code-a-thon-2018")};a.communityUnshare=
function(){a.busy=!0;d.unshareFromCommunity(a.projectId).then(function(){a.busy=!1;a.error="";a.success2="Successfully unpublished!";a.published=!1},function(b){a.busy=!1;a.success2="";a.error=b})};a.emailParent=function(){a.busy=!0;d.sendProjectEmail(a.projectId).then(function(){a.busy=!1;a.error="";a.success="Shared successfully!"},function(b){a.busy=!1;a.success="";a.error=b})};a.parentShare=function(){a.busy=!0;d.addToGallery(a.projectId,"home").then(function(){a.busy=!1;a.error="";a.success=
"Shared successfully!"},function(b){a.busy=!1;a.success="";a.error=b})};a.classShare=function(){a.busy=!0;d.addToGallery(a.projectId,"class").then(function(){a.busy=!1;a.error="";a.success="Shared successfully!"},function(b){a.busy=!1;a.success="";a.error=b})};a.defaultGalleryShare=function(){a.busy=!0;d.addToGallery(a.projectId,"gallery",prefs.defaultGalleryId).then(function(){a.busy=!1;a.error="";a.success="Shared successfully!"},function(b){a.busy=!1;a.success="";a.error=b})};a.emailShare=function(){a.busy=
!0;d.sendProjectEmail(a.projectId,a.displayName,a.email,a.captchaCode).then(function(){a.busy=!1;a.success="Shared successfully!"},function(b){a.busy=!1;a.error=b;a.generateCaptcha()})};a.facebookShare=function(){shareProjectFacebook(a.projectId,{appId:a.facebookAppId,serverName:b.host()})};a.twitterShare=function(){shareProjectTwitter(a.projectId,a.projectName,a.projectDescription,{serverName:b.host()})};a.googlePlusShare=function(){shareProjectGooglePlus(a.projectId,{serverName:b.host()})};a.generateCaptcha=
function(){a.captchaRandom="/api/captcha?r="+Math.random();a.captchaCode=null}}])})();(function(){angular.module("common.sharing").controller("SharingSetTitleCtrl",["$scope","$location",function(a,c){a.show=function(){$("#sharing-set-title").modal()};a.setTitle=function(a){IDE.setTitle(a);Runtime.stage.selectActor(null);var d=Runtime.stage.captureScreenshot();IDE._doProjectSave(a,null,d,!0,!0,function(a){a&&c.search({p:IDE.currentProjectId});a=$("#sharing").scope();a.show();a.$apply()})}}])})();
(function(){angular.module("common").factory("social",["$location","facebookAppId","stringUtils","requests",function(a,c,b,d){function f(b,e){var e=e?e:{},d=e.appId?e.appId:c,f=e.serverName?e.serverName:a.host(),d="https://www.facebook.com/dialog/share?"+$.param({app_id:d,display:"popup",href:b,redirect_uri:"http://"+f+"/api/closewindow"});window.open(d,"Share","toolbar=0,status=0,width=626,height=436")}function e(a,b,c){c=c?c:{};c=void 0!==c.hashTags?c.hashTags:"HourOfCode";a={url:a,text:b};c&&(a.hashtags=
c);a="https://twitter.com/intent/tweet?"+$.param(a);window.open(a,"Tweet","toolbar=0,status=0,width=626,height=436")}function g(a){a="https://plus.google.com/share?"+$.param({url:a});window.open(a,"Share on Google+","toolbar=0,status=0,width=626,height=436")}function h(a,b){var c="mailto:?subject="+encodeURIComponent(a)+"&body="+encodeURIComponent(b);window.open(c,"Share using e-mail","toolbar=0,status=0,width=626,height=436")}return{shareFacebook:f,shareTwitter:e,shareGooglePlus:g,shareEmail:h,shareProjectEmail:function(c,
e,f,g){g=g?g:{};d.get("/api/genshareurl",{id:c}).then(function(d){var n=g.serverName?g.serverName:a.host(),o=b.slugify(d.data.name);h(e,"\n\nTynker project made by "+f+"\n"+(g.shareUrl?g.shareUrl:"https://"+n+"/play/"+o+"/"+c+"-"+d.data.hash)+"\n")})},shareProjectFacebook:function(c,e){e=e?e:{};d.get("/api/genshareurl",{id:c}).then(function(d){var g=e.serverName?e.serverName:a.host(),h=b.slugify(d.data.name);f("https://"+g+"/play/"+h+"/"+c+"-"+d.data.hash,e)})},shareProjectTwitter:function(c,f,g,
h){h=h?h:{};d.get("/api/genshareurl",{id:c}).then(function(d){var g=h.serverName?h.serverName:a.host();h.hashTags=h.hashTags?h.hashTags:"tynker";var k=b.slugify(d.data.name);e(h.shareUrl?h.shareUrl:"https://"+g+"/play/"+k+"/"+c+"-"+d.data.hash,"Check out "+f+" a coding project created with Tynker",h)})},shareProjectGooglePlus:function(c,e){e=e?e:{};d.get("/api/genshareurl",{id:c}).then(function(d){var f=e.serverName?e.serverName:a.host(),h=b.slugify(d.data.name);g(e.shareUrl?e.shareUrl:"https://"+
f+"/play/"+h+"/"+c+"-"+d.data.hash)})},shareMyHocProjectTwitter:function(c,d,f,g){g=g?g:{};g.hashTags=g.hashTags?g.hashTags:"hourofcode,tynker";g.serverName||a.host();var f=g.serverName,h=b.slugify(d);e(g.shareUrl?g.shareUrl:"https://"+f+"/play/"+h+"/"+c,"I made "+d+" using code. Try it at",g)},shareMyHocProjectEmail:function(c,e,d,f){f=f?f:{};f.serverName=f.serverName?f.serverName:a.host();var d=f.serverName,g=b.slugify(e);h(e,"\n\nI made "+e+" using code. Try it at "+(f.shareUrl?f.shareUrl:"https://"+
d+"/play/"+g+"/"+c))}}}])})();(function(){function a(){return{bindToController:{uiSref:"="},controller:c,controllerAs:"vm",restrict:"A",link:function(a,c,f){var e=a.vm;e.element=c;c.click(function(){e.gotoState(f.uiSref)})}}}function c(a){var c=this;c.gotoState=function(f){if(!a.includes(f)){var e=c.element.parent();e&&"false"===e.attr("aria-expanded")&&a.go(f)}}}angular.module("common").directive("accordionParentLink",a);a.$inject=[];c.$inject=["$state"]})();
(function(){function a(){return{bindToController:{limit:"=?",blogClass:"=?",feedUrl:"=?",postClass:"=?"},controller:c,controllerAs:"vm",restrict:"E",scope:{},templateUrl:"/js/ng-app/common/blog.directive.html"}}function c(a,c,f){var e=this;e.extraClass=void 0!==e.extraClass?e.extraClass:null;e.feedUrl=void 0!==e.feedUrl?e.feedUrl:"https://www.tynker.com/blog/feed/";e.limit=void 0!==e.limit?e.limit:3;e.loading=!1;e.postClass=void 0!==e.postClass?e.postClass:"medium-6 large-4";e.posts=null;e.init=function(){e.loading=
!0;f.getBlogPosts(e.limit,e.feedUrl).then(function(f){e.posts=f.list.map(function(a){a.description=c.trustAsHtml(a.description);a.date=new Date(1E3*a.date);return a});setTimeout(function(){a&&a.find(".posts").foundation()});e.loading=!1},function(){e.loading=!1})};e.init()}angular.module("common").directive("blog",a);a.$inject=[];c.$inject=["$element","$sce","api"]})();
(function(){angular.module("common").directive("schoolBundlePreview",[function(){return{controller:["$scope","$timeout","api",function(a,c,b){a.bundle=null;a.showBundle=function(d){ga("send","event","School Bundle Preview","Open",d);a.isLoading=!0;b.getSchoolBundle(d).then(function(b){a.isLoading=!1;a.bundle=b;c(function(){angular.element(".school-bundle-preview").modal().one(angular.element.modal.BEFORE_CLOSE,function(){a.bundle=null})})},function(){a.isLoading=!1})}}],restrict:"E",scope:{},templateUrl:"/js/ng-app/common/schoolBundlePreview.directive.html"}}])})();
(function(){angular.module("common").directive("bundleQuickLook",[function(){return{controller:["$scope","$timeout","api",function(a,c,b){a.bundle=null;a.showBundle=function(d,f,e){ga("send","event","Bundle Quick Look","Open",d);a.childId=f;a.isSubscription=e?!0:!1;a.isLoading=!0;b.getBundle(d).then(function(b){a.ageRange=b.min_age+(b.max_age?"-"+b.max_age:"+");a.isLoading=!1;a.bundle=b;c(function(){angular.element(".bundle-preview").modal().one(angular.element.modal.BEFORE_CLOSE,function(){a.bundle=
null})})},function(){a.isLoading=!1})};a.addToCart=function(){ga("require","ec");ga("ec:addProduct",{id:a.bundle.bundle_licenseid,name:a.bundle.bundle_title,category:a.bundle.category,quantity:1});ga("ec:setAction","add");ga("send","event","Bundle Quick Look","Button Click","Add to Cart: "+a.bundle.bundle_title);var b="/cart/api/addtocart?sku="+a.bundle.bundle_licenseid,b=b+"&ec=0";a.childId&&(b+="&cid="+a.childId);window.location=b};a.subscribe=function(){ga("require","ec");ga("ec:addProduct",{id:a.bundle.bundle_licenseid,
name:a.bundle.bundle_title,category:a.bundle.category,quantity:1});ga("ec:setAction","add");ga("send","event","Bundle Quick Look","Button Click","Subscribe: "+a.bundle.bundle_title);var b="/cart/api/addtocart?sku="+a.bundle.subscription_licenseid,b=b+"&ec=0";a.childId&&(b+="&cid="+a.childId);window.location=b}}],restrict:"E",scope:{},templateUrl:"/js/ng-app/common/bundleQuickLook.directive.html"}}])})();
(function(){angular.module("common").directive("courseQuickLook",[function(){return{controller:["$scope","$timeout","api","modalPlans","switchUser",function(a,c,b,d,f){a.course=null;a.role=null;a.requiredPlan=null;a.globalSale=!1;a.coupon=null;a.showCourse=function(e,d,f){ga("send","event","Course Quick Look","Open",e);a.childId=d;a.isSubscription=f?!0:!1;a.isLoading=!0;b.getCourse(e,d).then(function(d){b.getRequiredPlanForCourse(e).then(function(e){b.getDiscounts().then(function(b){a.globalSale=
b.global_sale;a.coupon=b.coupon;a.isLoading=!1;a.course=d;a.hasCourse="student"==a.role&&d.is_user_licensed||"parent"==a.role&&d.is_child_licensed;a.galleryItems=d.kid_screenshots?d.kid_screenshots:d.screenshots;a.requiredPlan=e;c(function(){angular.element(".course-preview").modal().one(angular.element.modal.BEFORE_CLOSE,function(){a.course=null;a.galleryItems=null;angular.element(".thumbnail-gallery-wrap > .thumbnail-gallery-window > iframe").attr("src","/ide/imgs/blank.png")})})})})},function(){a.isLoading=
!1})};a.showCourseDetails=function(){ga("send","event","Course Quick Look","Link Click","Course Details: "+a.course.slug);var b="/courses/"+a.course.slug;a.childId&&(b+="?cid="+a.childId);window.location=b};a.buy=function(){ga("send","event","Course Quick Look","Link Click","Buy: "+a.course.slug);var b="/purchase/?c=buy&licenseid="+a.course.licenseid;a.childId&&(b+="&cid="+a.childId);window.location=b};a.switchUser=function(){b.getChildDisplayName(a.childId).then(function(b){f(a.childId,b)})};a.addToCart=
function(){ga("require","ec");ga("ec:addProduct",{id:a.course.licenseid,name:a.course.title,category:a.course.category,price:a.course.price_str,quantity:1});ga("ec:setAction","add");ga("send","event","Course Quick Look","Link Click","Add to Cart: "+a.course.slug);var b="/cart/api/addtocart?sku="+a.course.licenseid,b=b+"&ec=0";a.childId&&(b+="&cid="+a.childId);window.location=b};a.showPlans=function(){ga("send","event","Course Detail Page","Link Click","Subscribe: "+a.course.slug);d.open()};a.subscribe=
function(){ga("send","event","Course Quick Look","Button Click","Subscribe: "+a.course.slug);$.modal.close();window.location=b.SHOP_URL};a.viewSubscriptions=function(){ga("send","event","Course Quick Look","Link Click","View Subscriptions: "+a.course.slug);$.modal.close();window.location="#subscriptions"}}],restrict:"E",scope:{role:"@"},templateUrl:"/js/ng-app/common/courseQuickLookSubsOnly.directive.html"}}])})();
(function(){angular.module("common").directive("myDdslick",["$parse",function(a){return{restrict:"A",link:function(c,b,d){var f=a(d.ngModel),e=f.assign,g=!0;b.ddslick({showSelectedHTML:!1,onSelected:function(a){g?g=!1:f(c)!=a.selectedData.value&&(e(c,a.selectedData.value),c.load())}});c.$watch(d.ngModel,function(a){var c=b.attr("id")+"-dd-placeholder";$("#"+c).ddslick("select",{id:a})})}}}])})();
(function(){angular.module("common").directive("fileRead",[function(){return{scope:{fileRead:"="},link:function(a,c){c.bind("change",function(b){a.$apply(function(){a.fileRead=b.target.files[0]})})}}}])})();
(function(){angular.module("common").controller("GalleryCtrl",["$scope","$http","$location","api",function(a,c,b,d){a.location=b;a.error=null;a.galleryId=null;a.projectActivities=[];a.limit=16;a.skip=0;a.loading=!1;a.facebookAppId=null;a.originalProjectId=null;a.serverName="www.tynker.com";a.shareUrl="http://www.tynker.com/hour-of-code/projects";a.enablePopupShare=!0;a.enableShare=!1;a.enableRemix=!0;a.sort=null;a.init=function(c,e,d,h){a.facebookAppId=c;a.serverName=e;a.shareUrl=b.absUrl();a.galleryId=
d;a.sort=void 0!==h?h:{likecount:-1};a.projects=[];a.skip=0;a.load()};a.load=function(){if(!a.loading){var b={};a.originalProjectId&&(b.originalid=a.originalProjectId);a.loading=!0;d.getGalleryProjects(a.galleryId,b,a.sort,a.skip,a.limit).then(function(b){for(var c=0;c<b.length;c++)a.projects.push(b[c]);a.skip=a.skip+b.length;a.loading=false})}};a.likeProjectActivity=function(b){b.user_liked_project||d.likeProject(b._id.$id).then(function(){b.user_liked_project=!0;b.likecount+=1},function(b){a.error=
b})};a.playProject=function(b){Project.play(b.name,b._id.$id,{enableOpen:!1,enableSharing:!0,enableGoToProjectPage:!0,showProjectInformation:!0,showProjectConcepts:!1,facebookAppId:a.facebookAppId,serverName:a.serverName,embeddedShowViewCode:!0})};a.remixProject=function(a){window.location="/ide?p="+a._id.$id};a.setOriginalProjectId=function(b){a.originalProjectId=b;a.skip=0;a.projects=[];a.load()};a.shareProjectPopup=function(a){var b=$("#share-popup").scope();b&&b.show(a._id.$id,a.name)};a.shareProjectFacebook=
function(b){shareProjectFacebook(b._id.$id,{appId:a.facebookAppId,serverName:a.serverName})};a.shareProjectTwitter=function(a){shareProjectTwitter(a._id.$id,a.name)};a.shareProjectGooglePlus=function(a){shareProjectGooglePlus(a._id.$id)};a.shareProjectEmail=function(a){shareProjectEmail(a._id.$id,a.name,a.username)};a.sharePageFacebook=function(){shareFacebook(a.shareUrl,{appId:a.facebookAppId})};a.sharePageTwitter=function(){shareTwitter(a.shareUrl,"Check out the Hour of Code projects on Tynker",
{hashTags:"hourofcode,tynker"})};a.sharePageGooglePlus=function(){shareGooglePlus(a.shareUrl)};a.sharePageEmail=function(){shareEmail(a.shareUrl,"Check out the Hour of Code projects on Tynker")};a.sortByModified=function(){a.sort={modified:-1};a.skip=0;a.projects=[];a.load()};a.sortByLikecount=function(){a.sort={likecount:-1};a.skip=0;a.projects=[];a.load()};a._likeProjectActivity=function(b){b.user_liked=!1;a.likeProjectActivity(b)}}])})();
(function(){angular.module("common").directive("galleryCard",function(){return{restrict:"E",templateUrl:"/js/ng-app/common/galleryCard.directive.html"}})})();
(function(){angular.module("common").controller("HourOfCodeActivityListCtrl",["$scope","$window",function(a,c){a.expanded=!1;a.gradeRange="0-";a.showAllActivities=function(){a.gradeRange="-";c.scrollTo(0,0)};a.isGroupVisible=function(b){return"-"==a.gradeRange?!0:b==a.gradeRange};a.isShowingAllActivities=function(){return"-"==a.gradeRange};a.$watch("gradeRange",function(){a.expanded=!1})}])})();
(function(){var a=/^\-?\d+$/;angular.module("common").directive("integer",function(){return{require:"ngModel",link:function(c,b,d,f){f.$validators.integer=function(b,c){return f.$isEmpty(b)||a.test(c)?!0:!1}}}})})();
(function(){angular.module("common").directive("ngTooltipValidator",["$parse",function(a){return{restrict:"A",link:function(c,b,d){a(d.ngModel);var f=a(d.ngTooltipValidator);b.tipsy({trigger:"manual",gravity:"w"});c.$watch(d.ngModel,function(a){f(c)&&a&&f(c)(a,function(a){b.attr("title",a);b.tipsy("show")})})}}}])})();
(function(){function a(){return{controller:c,restrict:"A",link:function(a,c,f){c.click(function(){var a=angular.element("#"+f.openLightbox);a.find(".slider").slick("slickGoTo",f.slide);angular.element(window).resize();a.foundation();a.foundation("open")})}}}function c(){}angular.module("common").directive("openLightbox",a);a.$inject=[];c.$inject=[]})();
(function(){function a(){return{controller:c,restrict:"A",link:function(a,c,f,e){c.click(function(){e.show()})}}}function c(a){this.show=function(){a.open()}}angular.module("common").directive("openModalUpgrade",a);a.$inject=[];c.$inject=["modalUnlock"]})();
(function(){function a(a,b){a.filteredItems=[];a.groupedItems=[];a.itemsPerPage=null;a.pagedItems=[];a.currentPage=0;a.pageDistance=4;a.total=2*a.pageDistance+1;a.doSearch=!0;var d=function(){a.pagedItems=[];for(var b=a.filteredItems?a.filteredItems.length:null,e=0;e<b;e++)0===e%a.itemsPerPage?a.pagedItems[Math.floor(e/a.itemsPerPage)]=[a.filteredItems[e]]:a.pagedItems[Math.floor(e/a.itemsPerPage)].push(a.filteredItems[e])};a.search=function(){function f(b,d){for(var f=(a.filteredItems?a.filteredItems.length:
0)-1;0<f;--f)for(var i=0;i<f;++i){var j=a.filteredItems[i],k=a.filteredItems[i+1];if("last_login_date.sec"==b)var l=j.last_login_date?j.last_login_date.sec:null,m=k.last_login_date?k.last_login_date.sec:null;else"date_created.sec"==b?(l=j.date_created?j.date_created.sec:null,m=k.date_created?k.date_created.sec:null):"transaction_date.sec"==b?(l=j.transaction_date?j.transaction_date.sec:null,m=k.transaction_date?k.transaction_date.sec:null):(l=j[b],m=k[b]);d?m>l&&(a.filteredItems[i]=k,a.filteredItems[i+
1]=j):m<l&&(a.filteredItems[i]=k,a.filteredItems[i+1]=j)}}a.filteredItems=b("filter")(a.items,function(b){for(var d in b){var f;f=b[d];var i=a.searchText;f=i?f&&f.toLowerCase&&-1!==f.toLowerCase().indexOf(i.toLowerCase()):!0;if(f)return!0}return!1});""!==a.predicate&&f(a.predicate,a.reverse);d();a.currentPage=0;a.pageItems=a.pagedItems[a.currentPage]};a.range=function(a,b){var c=[];b||(b=a,a=0);for(var d=a;d<b;d++)c.push(d);return c};a.prevPage=function(){0<a.currentPage&&a.currentPage--};a.nextPage=
function(){a.currentPage<a.pagedItems.length-1&&a.currentPage++};a.setPage=function(b){a.currentPage=b};a.$watch("currentPage",function(){a.pageItems=a.pagedItems[a.currentPage]});a.$watch("items",function(){a.search()},!0);a.$watch("predicate",function(){a.search()});a.$watch("reverse",function(){a.search()});a.$on("do-search",function(){a.search()});a.$watch("itemsPerPage",function(){a.search()})}angular.module("common").directive("oldPagination",function(){return{controller:["$scope","$filter",
a],restrict:"E",templateUrl:"/js/ng-app/common/old-pagination.directive.html",scope:{itemsPerPage:"@",items:"=",pageItems:"=",predicate:"=",reverse:"=",searchText:"="}}})})();
(function(){angular.module("common").controller("ParentCoursePreviewCtrl",["$scope","api","modalPlans",function(a,c,b){a.course=null;a.showCourse=function(b,f,e){a.childId=f;a.isSubscription=e?!0:!1;a.isLoading=!0;c.getCourse(b).then(function(b){a.isLoading=!1;a.course=b;$(".course-preview").modal()},function(){a.isLoading=!1})};a.showCourseDetails=function(){ga("send","event","Parent Dashboard Course Information Modal","Link Click","Course Details: "+a.course.slug);var b="/courses/show?s="+a.course.slug;
a.childId&&(b+="&cid="+a.childId);window.location=b};a.addToCart=function(){ga("send","event","Parent Dashboard Course Information Modal","Link Click","Add to Cart: "+a.course.slug);var b="/cart/api/addtocart?sku="+a.course.licenseid;a.childId&&(b+="&cid="+a.childId);window.location=b};a.buy=function(){ga("send","event","Parent Dashboard Course Information Modal","Link Click","Buy: "+a.course.slug);var b="/purchase/?c=buy&licenseid="+a.course.licenseid;a.childId&&(b+="&cid="+a.childId);window.location=
b};a.showPlans=function(){ga("send","event","Course Detail Page","Link Click","Subscribe: "+a.course.slug);b.open()}}])})();
(function(){angular.module("common").directive("parentJoinRequestForm",[function(){return{controller:["$scope","$timeout","api",function(a,c,b){a.courseSlug=null;a.parentEmail=null;a.sent=!1;var d=null;a.sendParentJoinRequest=function(c){ga("send","event","Course Quick Look","Button Click","Ask Parents to Join: "+a.courseSlug);a.isLoading=!0;b.sendParentJoinRequest(c,a.courseSlug).then(function(){a.isLoading=!1;a.sent=!0},function(){a.isLoading=!1})};b.getMyParentEmail().then(function(b){a.parentEmail=
b});a.$watch("parentEmail",function(){a.parentEmail&&(d&&c.cancel(d),d=c(function(){b.canSend("parent-join-request",a.parentEmail).then(function(b){a.sent=!b})},300))})}],restrict:"E",scope:{courseSlug:"@"},templateUrl:"/js/ng-app/common/parentJoinRequestForm.directive.html"}}])})();(function(){angular.module("common").directive("preloadResource",["resourceCache",function(a){return{link:function(c,b,d){a.put(d.preloadResource,b.html())}}}])})();
(function(){function a(a,b,d,f){function e(a){if(!a)return null;var b=angular.element('a[href="#/'+g.category+'"]').text();return b?b:(b=a.replace(/-/g," ").replace(/\w\S*/g,function(a){return a.charAt(0).toUpperCase()+a.substr(1).toLowerCase()}))?b:a}var g=this,h="best-of-2013 best-of-2014 best-of-2015 featured hoc-animation hoc-art hoc-games hoc-stem hoc-stories peep recent".split(" ");g.location=b;g.error=null;g.category=null;g.categoryTitle=null;g.projects=[];g.projectActivities=[];g.limit=36;
g.skip=0;g.loading=!1;g.facebookAppId=null;g.serverName="www.tynker.com";g.shareUrl="http://www.tynker.com/hour-of-code/projects";g.enableBlock=!1;g.enableFeature=!1;g.enablePopupShare=!0;g.enableShare=!1;g.enableRemix=!0;g.enableReport=!0;g.hasMore=!1;g.init=function(d,f){g.enableBlock=d;g.enableFeature=f;g.parseUrl();a.$watch("vm.location.url()",function(a,b){a!=b&&g.parseUrl()});a.$watch("vm.category",function(){g.categoryTitle=e(g.category);g.shareUrl=b.absUrl();g.projects=[];g.projectActivities=
[];g.skip=0;g.load()});a.$on("projectReported",function(a,b){var c=g.projects.indexOf(b);-1<c&&g.projects.splice(c,1)})};g.load=function(){g.loading||(g.loading=!0,d.getProjectActivities(g.category,g.limit,g.skip).then(function(a){g.loading=!1;for(var b=0;b<a.length;b++){var c=a[b],e=c.projectid;g.projects.push({createdOn:c.timestamp?c.timestamp.sec:null,id:e,name:c.projectname,screenshot:"/assets/pscreenshot/"+e+".png",username:c.username,user_like:c.user_liked,views:c.views,likes:c.likes,projectActivity:{id:c._id}})}g.hasMore=
0<g.projects.length;g.skip+=g.projects.length},function(a){g.loading=!1;g.error=a}))};g.onScroll=function(){g.hasMore&&g.load()};g.parseUrl=function(){var a=b.url();a||(b.url("/recent"),a="/recent");a=a.replace("/","");0>h.indexOf(a)||(g.category=a)};g.sharePageFacebook=function(){var a=b.absUrl();f.shareFacebook(a)};g.sharePageTwitter=function(){b.absUrl();f.shareTwitter(g.shareUrl,"Check out the Hour of Code projects on Tynker",{hashTags:"hourofcode,tynker"})};g.sharePageGooglePlus=function(){b.absUrl();
f.shareGooglePlus(g.shareUrl)};g.sharePageEmail=function(){b.absUrl();f.shareEmail(g.shareUrl,"Check out the Hour of Code projects on Tynker")};g.toggleFeaturedProjectActivity=function(a){g.toggleProjectActivityTag(a,"featured")};g.toggleBlockedProjectActivity=function(a){g.toggleProjectActivityTag(a,"block")};g.toggleProjectActivityTag=function(a,b){g.isProjectActivityTagged(a,b)&&(b=null);d.tagProjectActivity(a._id.$id,b).then(function(b){a.tags=b},function(){alert(data.error)})};g._likeProjectActivity=
function(a){a.user_liked=!1;g.likeProjectActivity(a)};g.isProjectActivityFeatured=function(a){return g.isProjectActivityTagged(a,"featured")};g.isProjectActivityBlocked=function(a){return g.isProjectActivityTagged(a,"block")};g.isProjectActivityTagged=function(a,b){return a.tags&&-1!=a.tags.indexOf(b)}}angular.module("common").controller("ProjectActivityGalleryController",a);a.$inject=["$scope","$location","api","social"]})();
(function(){angular.module("common").directive("projectActivityGalleryCard",function(){return{restrict:"E",templateUrl:"/js/ng-app/common/projectActivityGalleryCard.directive.html"}})})();(function(){angular.module("common").factory("renderNotebook",function(){return function(a){return a.screenshot}})})();
(function(){function a(){return{controller:["modalPlans",function(a){this.showPlans=function(){a.open()}}],restrict:"A",link:function(a,b,d,f){b.click(function(){f.showPlans()})}}}angular.module("common").directive("showPlansQuickLook",a);a.$inject=[]})();(function(){angular.module("common").directive("showParentCourseQuickLook",[function(){return{controller:["modalCourseDetailsParent",function(a){this.showCourse=function(c){a.open({slug:c})}}],restrict:"A",link:function(a,c,b,d){c.click(function(){d.showCourse(b.showParentCourseQuickLook)})}}}])})();
(function(){angular.module("common").directive("slick",function(){return{restrict:"A",link:function(a,c,b){a={dots:!0,autoplay:!0,autoplaySpeed:5E3,focusOnSelect:!0};b.autoplaySpeed&&(a.autoplaySpeed=parseInt(b.autoplaySpeed));void 0!==b.fade&&(a.fade="true"==b.fade);void 0!==b.initial&&(a.initialSlide=parseInt(b.initial));void 0!==b.current&&b.$observe("current",function(a){a!=""&&angular.element("#course-slider").slick("slickGoTo",a)});void 0!==b.autoplay&&(a.autoplay="true"==b.autoplay);b.slidestoshow&&
(a.slidesToShow=parseInt(b.slidestoshow));b.slidestoscroll&&(a.slidesToScroll=parseInt(b.slidestoscroll));void 0!==b.centermode&&(a.centerMode="true"==b.centermode);void 0!==b.focusonselect&&(a.focusOnSelect="true"==b.focusonselect);void 0!==b.infinite&&(a.infinite="true"==b.infinite);c.slick(a).find(".slide").removeClass("hidden")}}})})();
(function(){angular.module("common").directive("slickContent",function(){return{restrict:"A",link:function(a,c){c.find(".slick-initialized").on("afterChange",function(b,c,f){"function"==typeof a.changeCourse&&a.changeCourse(f)})}}})})();(function(){angular.module("common").directive("slickReveal",function(){return{restrict:"A",link:function(a,c){$(window).trigger("resize");c.parents(".reveal").on("open.zf.reveal",function(){angular.element("#overview-slider").slick("setPosition",0)})}}})})();
(function(){angular.module("common").directive("studentActivityPreview",[function(){return{controller:["$scope","$timeout","api",function(a,c,b){a.activity=null;a.isLoading=!1;a.showActivity=function(d,f){a.isLoading=!0;b.getActivity(d).then(function(b){a.isLoading=!1;a.isLocked=f?!0:!1;a.activity=b;$(".activity-preview").modal();c(function(){$.modal.resize()});$(document).one($.modal.CLOSE,function(){a.activity=null;a.$apply()})},function(){a.isLoading=!1})};a.resendParentVerificationEmail=function(){ga("send",
"event","Account Verification","Verification Request","U13 Account Verification Request: "+a.activity.slug);a.isLoading=!0;b.resendParentVerificationEmail().then(function(){a.isLoading=!1;a.sent=!0},function(){a.isLoading=!1})}}],restrict:"E",scope:{sent:"="},templateUrl:"/js/ng-app/common/studentActivityPreview.directive.html"}}])})();
(function(){angular.module("common").directive("studentCoursePreview",[function(){return{controller:["$scope","$timeout","api","modalPlans",function(a,c,b,d){a.course=null;a.sent=!1;a.requiredPlan=null;a.addToCart=function(){ga("send","event","Student Course Popup","Link Click","Add to Cart: "+a.course.slug);window.location="/cart/api/addtocart?sku="+a.course.licenseid};a.buy=function(){ga("send","event","Student Course Popup","Link Click","Buy: "+a.course.slug);window.location="/purchase/?c=buy&licenseid="+
a.course.licenseid};a.showCourse=function(d,e){a.isLoading=!0;b.getCourse(d).then(function(g){b.getRequiredPlanForCourse(d).then(function(b){a.isLoading=!1;a.isSubscription=e?!0:!1;a.course=g;a.galleryItems=g.kid_screenshots?g.kid_screenshots:g.screenshots;a.requiredPlan=b;$(".course-preview").modal();c(function(){$.modal.resize()});$(document).one($.modal.CLOSE,function(){a.course=null;a.galleryItems=null;a.$apply()})})},function(){a.isLoading=!1})};a.showCourseDetails=function(){ga("send","event",
"Student Course Popup","Button Click","Course Details: "+a.course.slug);window.location="/courses/show?s="+a.course.slug};a.showPlans=function(){ga("send","event","Course Detail Page","Link Click","Subscribe: "+a.course.slug);d.open()};a.subscribe=function(){ga("send","event","Student Course Popup","Button Click","Subscribe Now");window.location=b.SHOP_URL};a.sendParentSubscriptionRequest=function(c){ga("send","event","Student Course Popup","Button Click","Ask Parents to Enroll: "+a.course.slug);
a.isLoading=!0;b.sendParentSubscriptionRequest(c,a.course.slug).then(function(){a.isLoading=!1;a.sent=!0},function(){a.isLoading=!1})};b.getMyParentEmail().then(function(b){a.parentEmail=b})}],restrict:"E",templateUrl:"/js/ng-app/common/studentCoursePreview.directive.html"}}])})();
(function(){function a(){return{bindToController:{endsOn:"@"},controller:c,controllerAs:"vm",restrict:"E",scope:{},templateUrl:"/js/ng-app/common/sale-countdown.directive.html"}}function c(a){function c(){e-=g;1>e?(f.isOver=!0,a.cancel(f.promise)):f.isOver=!1}var f=this,e=null,g=1E3;f.init=function(){var h=Date.now();e=1E3*parseFloat(f.endsOn)-h;f.promise=a(c,g);c()};f.isOver=null;f.init()}angular.module("common").directive("saleCountdown",a);a.$inject=[];c.$inject=["$interval","$timeout"]})();
(function(){angular.module("common").directive("uniqueUsername",["api",function(a){return{require:"ngModel",link:function(c,b,d,f){f.$asyncValidators.uniqueUsername=function(b,c){return a.validateUsername(b||c)}}}}])})();(function(){angular.module("common").directive("wizardActions",function(){return{restrict:"E",templateUrl:"/js/ng-app/common/wizardActions.directive.html",scope:{busy:"=",hasPrevious:"=",hasNext:"=",previous:"=",next:"=",form:"="}}})})();(function(){angular.module("components",["ngCookies"])})();
(function(){angular.module("common").directive("codeySlider",[function(){return{controller:["$scope","$timeout",function(a,c){a.labels=[];a.values=[];a.value=null;a.index=null;a.cursorMarginLeft=null;a.cursorLeft=null;a.cursorX=null;a.draggingCursor=!1;a.cursorMousedown=function(b){a.draggingCursor=!0;a.lastX=b.pageX;angular.element("body").one("mouseup",function(){c(function(){a.draggingCursor=!1;a.cursorMouseup()})})};a.cursorMouseup=function(){a.draggingCursor=!1;var b=Math.round(a.cursorX/100*
a.values.length);c(function(){a.setIndex(b)})};a.cursorMousemove=function(b){a.draggingCursor&&(c(function(){a.deltaX=(b.pageX-a.lastX)/a.lastX;a.lastX=b.pageX;a.setCursorX(a.cursorX+100*a.deltaX)}),console.log(a.cursorX))};a.init=function(){a.index=0;angular.element("body").keyup(function(b){var d=a.index;37==b.keyCode&&d--;39==b.keyCode&&d++;c(function(){a.setIndex(d)})})};a.setCursorX=function(b){0>b&&(b=0);100<b&&(b=100);a.cursorX=b};a.setIndex=function(b){0>b&&(b=0);b>a.values.length-1&&(b=a.values.length-
1);a.value=a.values[b];a.cursorX=100*(a.index/(a.values.length-1))};a.$watch("value",function(){a.index=a.values.indexOf(a.value);a.label=a.labels[a.index];a.model=a.value});a.$watch("model",function(){a.value=a.model});a.$watch("index",function(){a.cursorX=100*(a.index/(a.values.length-1))});a.$watch("cursorX",function(){a.cursorLeft=a.cursorX+"%";a.cursorMarginLeft="0 0 0 "+-8*(6+a.index)+"px"});a.init()}],link:function(a,c){a.sticky&&c.find(".codey-slider").waypoint("sticky",{offset:60})},restrict:"E",
scope:{model:"=",sticky:"="},transclude:!0,templateUrl:"/js/ng-app/components/codeySlider.directive.html"}}]).directive("codeySliderOption",function(){return{controller:["$scope",function(a){a.setSliderValue=function(c){a.$parent.$parent.value=c};a.$watch("$parent.$parent.value",function(c){a.selected=c==a.value})}],link:function(a,c,b){c=c.find("[ng-transclude]").find("span").text();a.$parent.$parent.values.push(a.value);a.$parent.$parent.labels.push(c);void 0!==b.selected&&"false"!==b.selected&&
a.setSliderValue(a.value)},restrict:"E",scope:{value:"@"},transclude:!0,templateUrl:"/js/ng-app/components/codeySliderOption.directive.html"}})})();
(function(){angular.module("common").directive("collapsiblePanel",function(){return{controller:["$scope","$parse",function(a,c){var b=c(a.collapse),d=c(a.expand);a.collapsePanel=function(){a.collapsed=!0;b(a.$parent)};a.expandPanel=function(){a.collapsed=!1;d(a.$parent)};a.init=function(){a.collapsed=angular.isDefined(a.collapsed)?a.collapsed:!1;a.collapseLabel=angular.isDefined(a.collapseLabel)?a.collapseLabel:"Collapse";a.expandLabel=angular.isDefined(a.expandLabel)?a.expandLabel:"Expand"};a.init()}],
transclude:!0,restrict:"E",scope:{collapseIconClass:"@",collapseLabel:"@",expandLabel:"@",expandIconClass:"@",collapse:"@",collapsed:"=?",expand:"@"},templateUrl:"/js/ng-app/components/collapsiblePanel.directive.html"}})})();
(function(){function a(a,b,d){b.optimizely=b.optimizely||[];a.subscriptionId=null;a.steps=["join","profile","thanks"];a.step="join";a.role="parent";a.join=function(){d.addSubscription({email:a.email,role:a.role,strict:!1,type:"email-collector-banner"}).then(function(b){a.subscriptionId=b;a.step="profile";a.error=null;ga("send","event","Email Collector Banner","Submit")},function(b){a.error=b});b.optimizely.push(["trackEvent","emailCollectorFormSubmitted"]);b.optimizely.push(["trackEvent",a.role+"EmailCollectorFormSubmitted"])};
a.updateProfile=function(){d.updateSubscription(a.subscriptionId,{fname:a.fname,lname:a.lname,email:a.email,role:a.role,strict:!1,type:"email-collector-banner"}).then(function(){a.error=null;a.step="thanks";ga("send","event","Email Collector Banner","Complete")});b.optimizely.push(["trackEvent","emailCollectorFormCompleted"]);b.optimizely.push(["trackEvent",a.role+"EmailCollectorFormCompleted"])}}angular.module("common").directive("emailCollectorBanner",function(){return{controller:["$scope","$window",
"api",a],templateUrl:"/js/ng-app/components/emailCollectorBanner.directive.html",restrict:"E",scope:{role:"@"}}})})();
(function(){function a(a){var b;a.timeoutTriggerSeconds=2;a.triggerOnMouseOut=!1;a.triggerOnTimeout=!0;a.canOpen=function(){var a=angular.element.cookie("dismissed_mc_edit_ad_modal"),b=angular.element.modal.isActive()||angular.element("body").hasClass("is-reveal-open");return!a&&!b};a.onClose=function(){a.isOpen=!1;ga("send","event","Minecraft Editor Ad Modal","Dismiss");angular.element.cookie("dismissed_mc_edit_ad_modal",!0,{expires:30,path:"/"})};a.openModal=function(d){if(!a.isOpen&&(a.canOpen()||
void 0!==d&&d))a.isOpen=!0,d=angular.element("#minecraft-editor-ad-modal"),d.one("closed.zf.reveal",a.onClose),b||(b=new Foundation.Reveal(d)),b.open(),ga("send","event","Minecraft Editor Ad Modal","Show")};a.init=function(){angular.element(".js-open-minecraft-editor-ad-modal").click(function(){a.openModal(!0)});a.canOpen()&&(a.isOpen=!1,a.triggerOnMouseOut&&angular.element(document).bind("mouseout",function(b){b=b?b:window.event;b=b.relatedTarget||b.toElement;(!b||"HTML"===b.nodeName)&&a.openModal()}),
a.triggerOnTimeout&&setTimeout(function(){a.openModal()},1E3*a.timeoutTriggerSeconds))};a.init()}angular.module("common").directive("minecraftEditorAdModal",function(){return{controller:["$scope","$window","api",a],templateUrl:"/js/ng-app/components/minecraftEditorAdModal.directive.html",restrict:"E",scope:{}}})})();
(function(){angular.module("common").directive("newBadge",[function(){return{restrict:"A",link:function(a,c){var b=c.css("display"),b=b?b:"block",d=c.css("margin");c.css("margin","0px");var f=c.css("vertical-align"),e=c.wrap("<div class='new-badge-container'></div>").parent();e.css("display",b);e.css("margin",d);e.css("vertical-align",f);e.append("<div class='new-badge'></div>")}}}])})();
(function(){function a(){return{controller:c,controllerAs:"vm",restrict:"A",link:function(a,c,f,e){c.click(function(){e.open(f)})}}}function c(a){this.open=function(c){a.play(c.openModalVideo,c)}}angular.module("common.account").directive("openModalVideo",a);a.$inject=[];c.$inject=["modalVideo"]})();
(function(){function a(a){var b=this;b.selectResult=function(a){b.selectedResult=a;b.searchQuery=b.getResultDisplay(a);b.resultsVisible=!1};b.getResultDisplay=function(a){return a[b.resultDisplayAttribute]};b.resultIdAttribute=void 0!==b.resultIdAttribute?b.resultIdAttribute:"id";b.resultDisplayAttribute=void 0!==b.resultDisplayAttribute?b.resultDisplayAttribute:"title";b.resultsVisible=!1;a.$watch("vm.searchQuery",function(){var a=b.selectedResult?b.getResultDisplay(b.selectedResult):null;b.searchQuery!=
a&&(b.selectedResult=null,b.resultsVisible=!b.selectedResult&&b.results&&0<b.results.length?!0:!1)});a.$watch("vm.results",function(){b.resultsVisible=!b.selectedResult&&b.results&&0<b.results.length?!0:!1})}angular.module("components").directive("searchDropDown",function(){return{bindToController:{searchQuery:"=",selectedResult:"=",results:"=",resultIdAttribute:"=",resultDisplayAttribute:"="},controller:a,controllerAs:"vm",restrict:"E",scope:{},templateUrl:"/js/ng-app/components/search-drop-down.directive.html"}});
a.$inject=["$scope"]})();(function(){function a(a){var b=this;b.play=function(){a.play(b.video,{gaCategory:"Hour of Code Teacher Page"})}}angular.module("common").directive("videoThumbnail",function(){return{bindToController:{thumb:"@",video:"@",comment:"@"},controller:a,controllerAs:"vm",replace:!0,restrict:"E",templateUrl:"/js/ng-app/components/videoThumbnail.directive.html",scope:{}}});a.$inject=["modalVideo"]})();(function(){angular.module("site","angularMoment ui.router infinite-scroll common common.account site.account site.hourOfCode site.minecraft site.store".split(" "))})();
(function(){angular.module("site.account",[])})();
(function(){angular.module("site.account").controller("JoinCtrl",["$scope","$state","$window","api","externalAuth",function(a,c,b,d,f){a.state=c;a.error=null;a.busy=!1;a.signupUser=function(e){a.busy=!0;return d.addUser(e).then(function(){a.onLoginSuccess();try{b.optimizely=b.optimizely||[],b.optimizely.push(["trackEvent",e.role+"_account_created"])}catch(c){console.log(c)}},function(b){a.busy=!1;a.error=b})};a.validateUsername=function(a,b){a?6>a.length?b("Screen name must have at least 6 characters"):
d.validateUsername(a).then(function(){b("Looking good!")},function(){b("Sorry, that screen name is already taken.")}):b("You must provide a screen name")};a.validatePassword=function(a,b){a?6>a.length?b("Password must have at least 6 characters"):b("Ok!"):b("You must provide a password.")};a.validateEmail=function(a,b){a?-1==a.indexOf("@")?b("Doesn't look like a valid email"):d.validateEmail(a).then(function(){b("Ok")},function(){b("Doesn't look like a valid email")}):b("You must provide a valid email address")};
a.googleLogin=function(b){b=void 0!==b?b:{};b.source=void 0!==b.source?b.source:"join";f.googleLogin(b).then(function(){a.onLoginSuccess()},function(b){a.error=b})};a.facebookLogin=function(b){b=void 0!==b?b:{};b.source=void 0!==b.source?b.source:"join";f.facebookLogin(b).then(function(){a.onLoginSuccess()},function(b){a.error=b})};a.azureLogin=function(b){b=void 0!==b?b:{};b.source=void 0!==b.source?b.source:"join";f.azureLogin(b).then(function(){a.onLoginSuccess()},function(b){a.error=b})};a.onLoginSuccess=
function(a){$(document).trigger("common.account.loggedIn",[a])};a.$on("$viewContentLoaded",function(){setTimeout(function(){$("#join-view > .modal").length&&$("#join-view > .modal").modal()},0)})}])})();
(function(){angular.module("site.account").controller("SignInCtrl",["$scope","$state","$http","api","externalAuth",function(a,c,b,d,f){a.error=null;a.user={};a.busy=!1;a.login=function(){a.busy=!0;d.login(a.user.u,a.user.p).then(function(){a.onLoginSuccess(c.params.next)},function(b){a.busy=!1;a.error=b})};a.googleLogin=function(b){var b=void 0!==b?b:{},d=c.params.next?c.params.next:null;!b.next&&d&&(b.next=d);f.googleLogin(b).then(function(){a.onLoginSuccess(d)},function(b){a.error=b})};a.facebookLogin=
function(b){var b=void 0!==b?b:{},d=c.params.next?c.params.next:null;!b.next&&d&&(b.next=d);f.facebookLogin(b).then(function(){a.onLoginSuccess(d)},function(b){a.error=b})};a.azureLogin=function(b){var b=void 0!==b?b:{},d=c.params.next?c.params.next:null;!b.next&&d&&(b.next=d);f.azureLogin(b).then(function(){a.onLoginSuccess(d)},function(b){a.error=b})}}]).controller("CheckoutSignInCtrl",["$scope","$http","api","externalAuth",function(a,c,b,d){a.userType=null;a.error=null;a.user={};a.busy=!1;a.login=
function(){a.busy=!0;b.login(a.user.u,a.user.p).then(function(b){ga("ec:setAction","checkout",{step:1,option:"sign-in_Tynker-"+b.role});a.onLoginSuccess()},function(b){a.busy=!1;a.error=b})};a.googleLogin=function(b){b=void 0!==b?b:{};d.googleLogin(b).then(function(){ga("ec:setAction","checkout",{step:1,option:"sign-in_Google"});a.onLoginSuccess()},function(b){a.error=b})};a.azureLogin=function(b){b=void 0!==b?b:{};d.azureLogin(b).then(function(){ga("ec:setAction","checkout",{step:1,option:"sign-in_Azure"});
a.onLoginSuccess()},function(b){a.error=b})};a.init=function(b,c){a.user.u=b?b:null;a.userType=c?c:"new"};a.facebookLogin=function(b){b=void 0!==b?b:{};d.facebookLogin(b).then(function(){ga("ec:setAction","checkout",{step:1,option:"sign-in_Facebook"});a.onLoginSuccess()},function(b){a.error=b})}}])})();(function(){angular.module("site.hourOfCode",["common"])})();
(function(){function a(a,b){var d=this;d.category=null;d.categories=[];d.hasMore=!1;d.init=function(){d.initialized||(b.getExploreCategories().then(function(a){d.categories=a["Hour of Code"];d.category="recent"}),a.$watch("vm.category",function(){d.projects=[];d.load()}),a.$on("projectReported",function(a,b){var c=d.projects.indexOf(b);-1<c&&d.projects.splice(c,1)}),d.initialized=!0)};d.initialized=!1;d.projects=[];d.loading=!1;d.load=function(){d.loading=!0;b.getProjectActivities(d.category,50,d.skip).then(function(a){d.hasMore=
0<a.length;for(var b=0;b<a.length;b++){var c=a[b],h=c.projectid;d.projects.push({createdOn:c.timestamp?c.timestamp.sec:null,id:h,name:c.projectname,screenshot:"/assets/pscreenshot/"+h+".png",username:c.username,user_liked:c.user_liked,views:c.views,likes:c.likes,projectActivity:{id:c._id}})}d.loading=!1},function(a){d.loading=!1;d.error=a})};d.loadMore=function(){d.skip+=d.projects.length;d.load()};d.skip=0}angular.module("site.hourOfCode").controller("HourOfCodeActivityListController",a);a.$inject=
["$scope","api"]})();(function(){angular.module("site.minecraft",["common","components"])})();(function(){angular.module("site.minecraft").controller("ModCardCtrl",["$scope","modalCourseDetailsStudent",function(a,c){a.showCourse=function(a){c.open({slug:a})}}])})();
(function(){function a(a,b,d){function f(){d.getCourseDetails(g.id).then(function(a){g.loading=!1;g.display=a.list;console.log(a.list);e()},function(){g.loading=!1})}function e(){var a=angular.element(document.querySelector("#description"));g.display.activeCourses[g.currentIndex].description_no_concepts?a.html(g.display.activeCourses[g.currentIndex].description_no_concepts):a.html(g.display.activeCourses[g.currentIndex].description)}var g=this;g._class=null;g.display=null;g.current=null;g.loading=
!1;g.id=a.courseid;g.currentIndex=0;g.init=function(){g.id=a.courseid;g.loading=!0;f()};g.init();a.changeCourse=function(b){g.id=g.display.activeCourses[b].id;g.currentIndex=b;a.$apply();e()}}angular.module("site").directive("courseDetailsPage",function(){return{restrict:"EA",controller:a,controllerAs:"vm",scope:{courseid:"="},templateUrl:"/js/ng-app/site/course-details-page.directive.html",link:function(a,b,d){b.foundation();a.id=d.id;a.currentIndex=d.currentIndex}}});a.$inject=["$scope","$state",
"api"]})();
(function(){angular.module("site").controller("CourseCatalogCtrl",["$scope","api",function(a,c){var b=0;a.ageRange="7-";a.currentCourse=null;a.courses=null;a.collapsed=!0;a.applyFilters=function(){a.filteredCourses=[];for(var b=0;2>b;b++)a.filteredCourses.append(a.courses[b])};a.init=function(){a.getCourses()};a.getCourses=function(){b=0;c.getCourses("home",b,100).then(function(b){a.courses=b.list;a.currentPage=Math.floor(b.current/100);a.totalPages=Math.floor(b.total/100)})};a.more=function(){b++;c.getCourses("home",
b,100).then(function(b){a.courses=a.courses.concat(b.list);a.currentPage=Math.floor(b.current/100);a.totalPages=Math.floor(b.total/100)})};a.selectCourse=function(b){$window.scrollTo(0,0);a.currentCourse=b};a.showBundle=function(a){angular.element(".bundle-quick-look").scope().showBundle(a)};a.showCourse=function(a){angular.element(".course-quick-look").scope().showCourse(a)};a.isBundleVisible=function(b){return a.currentBundleAgeRange==b}}]).controller("CheckoutRedeemTeacherCtrl",["$scope","api",
function(a,c){a.busy=!1;a.error=null;a.teacher=null;a.login=function(){a.busy=!0;c.login(a.username,a.password).then(function(){window.location="/store/checkout/redeem/teacher?c=setFromSession"},function(b){a.busy=!1;a.error=b})};a.addUser=function(){var b={username:a.username,password:a.password,role:"teacher",log_in:!0,confirmed:!0};a.busy=!0;c.addUser(b).then(function(){window.location="/store/checkout/redeem/teacher?c=setFromSession"},function(b){a.busy=!1;a.error=b})};a.init=function(b){a.username=
b}}]).controller("CheckoutRedeemCampCtrl",["$scope","api",function(a,c){a.busy=!1;a.error=null;a.camp=null;a.addUser=function(){var b={username:a.username,password:a.password,role:"teacher",log_in:!0,confirmed:!0};a.busy=!0;c.addUser(b).then(function(){window.location="/store/checkout/redeem/camp?c=setFromSession"},function(b){a.busy=!1;a.error=b})};a.init=function(b){a.username=b}}])})();
(function(){angular.module("site").directive("toggleParentClass",function(){return{restrict:"A",link:function(a,c,b){c.bind("click",function(){c.parent().toggleClass(b.toggleParentClass)})}}})})();
(function(){angular.module("site").controller("PartnerLeadFormCtrl",["$scope","$http","api",function(a,c,b){a.lead={};a.captchaRandom=null;a.error=null;a.message=null;a.init=function(){a.generateCaptcha()};a.submit=function(){a.error=null;b.addLead(a.lead).then(function(){a.error=null;a.message="Thank you! You will soon be contacted by someone on our team"},function(b){a.error=b;a.generateCaptcha()})};a.generateCaptcha=function(){a.captchaRandom=Math.random()};a.init()}])})();
